module 6 task 2
js-tasks-ru/jsbasic-20220711_elvvvirk pull request #10
Opened 2022-08-10 21:10 UTC by elviraff

2022-08-10 21:11 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-11 10:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-08-11 13:17 UTC, SinimaWath requested changes

2022-08-11 13:17 UTC, SinimaWath commented on 6-module/2-task/index.js
> +})
Убери лишний код из функции, это в будущем может поломать тебе остальные задачи

2022-08-11 13:17 UTC, SinimaWath commented on 6-module/3-task/index.js
> +document.addEventListener('product-add', (event) => {
тут тоже убери код, для тестирования

2022-08-11 13:17 UTC, SinimaWath commented on 6-module/3-task/index.js
> +      detail: event.currentTarget.closest('.carousel__slide').getAttribute('data-id'),
`event.currentTarget.closest('.carousel__slide').dataset.id`

2022-08-11 16:23 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-12 19:55 UTC, SinimaWath approved these changes

2022-08-12 19:55 UTC, merged