module 3 tasks 4-5
js-tasks-ru/jsbasic-20220711_elvvvirk pull request #6
Opened 2022-07-31 22:11 UTC by elviraff

2022-07-31 22:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-01 14:40 UTC, SinimaWath requested changes

2022-08-01 14:40 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
Получилось сложновато. Раздели на 3 этапа:

`return users.filter(...).map(...).join('\n')`

2022-08-01 14:40 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  result = {}
Это не создание переменной, у тебя тут нет let/const

2022-08-01 21:06 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-01 21:07 UTC, elviraff commented on 3-module/4-task/index.js
> +  });
блин, точно, спасибо!

2022-08-02 11:34 UTC, SinimaWath approved these changes

2022-08-02 11:35 UTC, merged